"""Username / handle profile URL catalog (not email registration).

Edit this file to grow the username presence collection.
Email sites: built-in pack (~121) + core/extra_email_sites.py
Full inventory: docs/SITES_CATALOG.md
"""

SITES = [
    {"id": "github", "name": "GitHub", "url": "https://github.com/{u}", "kind": "github"},
    {"id": "gitlab", "name": "GitLab", "url": "https://gitlab.com/{u}", "kind": "gitlab"},
    {"id": "bitbucket", "name": "Bitbucket", "url": "https://bitbucket.org/{u}/", "kind": "html",
     "not_found": ("repository not found", "page not found"), "found": ("bitbucket", "aui-avatar")},
    {"id": "reddit", "name": "Reddit", "url": "https://www.reddit.com/user/{u}", "kind": "reddit"},
    {"id": "devto", "name": "Dev.to", "url": "https://dev.to/{u}", "kind": "devto"},
    {"id": "hackernews", "name": "Hacker News", "url": "https://news.ycombinator.com/user?id={u}", "kind": "hackernews"},
    {"id": "stackoverflow", "name": "Stack Overflow", "url": "https://stackoverflow.com/users/{u}", "kind": "html",
     "not_found": ("page not found", "user not found"), "found": ("user-card", "profile")},
    {"id": "codepen", "name": "CodePen", "url": "https://codepen.io/{u}", "kind": "html",
     "not_found": ("404", "not found"), "found": ("profile-username", "og:title")},
    {"id": "replit", "name": "Replit", "url": "https://replit.com/@{u}", "kind": "html",
     "not_found": ("not found", "doesn't exist"), "found": ("replit", "profile")},
    {"id": "npm", "name": "npm", "url": "https://www.npmjs.com/~{u}", "kind": "html",
     "not_found": ("not found", "couldn't find"), "found": ("packages",)},
    {"id": "pypi", "name": "PyPI", "url": "https://pypi.org/user/{u}/", "kind": "html",
     "not_found": ("not found", "404"), "found": ("profile", "packages")},
    {"id": "dockerhub", "name": "Docker Hub", "url": "https://hub.docker.com/u/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("docker", "repositories")},
    {"id": "huggingface", "name": "Hugging Face", "url": "https://huggingface.co/{u}", "kind": "html",
     "not_found": ("not found", "doesn't exist"), "found": ("huggingface", "profile")},
    {"id": "kaggle", "name": "Kaggle", "url": "https://www.kaggle.com/{u}", "kind": "html",
     "not_found": ("404", "not found"), "found": ("kaggle", "profile")},
    {"id": "instagram", "name": "Instagram", "url": "https://www.instagram.com/{u}/", "kind": "html",
     "not_found": ("sorry, this page isn't available", "page isn't available"),
     "found": ('og:type" content="profile"', "profilepage_", '"username":')},
    {"id": "facebook", "name": "Facebook", "url": "https://www.facebook.com/{u}", "kind": "html",
     "not_found": ("this content isn't available", "page isn't available", "content not found"),
     "found": ("fb://profile/", 'og:type" content="profile"')},
    {"id": "twitter", "name": "X (Twitter)", "url": "https://x.com/{u}", "kind": "html",
     "not_found": ("this account doesn’t exist", "this account doesn't exist", "account doesn't exist"),
     "found": ('property="og:type" content="profile"',)},
    {"id": "threads", "name": "Threads", "url": "https://www.threads.net/@{u}", "kind": "html",
     "not_found": ("page isn't available", "isn't available right now"),
     "found": ('og:type" content="profile"',)},
    {"id": "bluesky", "name": "Bluesky", "url": "https://bsky.app/profile/{u}.bsky.social", "kind": "html",
     "not_found": ("not found", "unable to resolve"), "found": ("bsky", "profile")},
    {"id": "mastodon", "name": "Mastodon", "url": "https://mastodon.social/@{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("mastodon", "account")},
    {"id": "tiktok", "name": "TikTok", "url": "https://www.tiktok.com/@{u}", "kind": "html",
     "not_found": ("couldn't find this account", "page not available"),
     "found": ("uniqueid", "tiktok-uniqueid", 'og:type" content="profile"')},
    {"id": "youtube", "name": "YouTube", "url": "https://www.youtube.com/@{u}", "kind": "html",
     "not_found": ("this page isn't available", "404 not found"),
     "found": ('itemprop="name"', "og:video", "channelid")},
    {"id": "twitch", "name": "Twitch", "url": "https://www.twitch.tv/{u}", "kind": "html",
     "not_found": ("sorry. unless you’ve got a time machine", "this channel is unavailable"),
     "found": ("islivebroadcast", "tw-channel-name")},
    {"id": "telegram", "name": "Telegram", "url": "https://t.me/{u}", "kind": "html",
     "not_found": ("if you have telegram, you can contact",),
     "found": ("tgme_page_title", "tgme_page_photo")},
    {"id": "snapchat", "name": "Snapchat", "url": "https://www.snapchat.com/add/{u}", "kind": "html",
     "not_found": ("not found", "page not found"), "found": ("snapchat", "add")},
    {"id": "linkedin", "name": "LinkedIn", "url": "https://www.linkedin.com/in/{u}", "kind": "html",
     "not_found": ("this page doesn’t exist", "this page doesn't exist", "page not found"),
     "found": ('og:type" content="profile"', "urn:li:member:")},
    {"id": "medium", "name": "Medium", "url": "https://medium.com/@{u}", "kind": "html",
     "not_found": ("out of luck", "page not found"),
     "found": ('property="og:type" content="profile"',)},
    {"id": "hashnode", "name": "Hashnode", "url": "https://hashnode.com/@{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("hashnode", "profile")},
    {"id": "substack", "name": "Substack", "url": "https://substack.com/@{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("substack", "profile")},
    {"id": "pinterest", "name": "Pinterest", "url": "https://www.pinterest.com/{u}/", "kind": "html",
     "not_found": ("user not found", "page not found"),
     "found": ('og:type" content="profile"', "pinterestapp:followers")},
    {"id": "tumblr", "name": "Tumblr", "url": "https://{u}.tumblr.com", "kind": "html",
     "not_found": ("not found", "there's nothing here"), "found": ("tumblr", "blog")},
    {"id": "flickr", "name": "Flickr", "url": "https://www.flickr.com/people/{u}/", "kind": "html",
     "not_found": ("page not found", "not found"), "found": ("flickr", "profile")},
    {"id": "vimeo", "name": "Vimeo", "url": "https://vimeo.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("vimeo", "profile")},
    {"id": "soundcloud", "name": "SoundCloud", "url": "https://soundcloud.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("soundcloud", "profile")},
    {"id": "spotify", "name": "Spotify", "url": "https://open.spotify.com/user/{u}", "kind": "html",
     "not_found": ("not found", "page not found"), "found": ("spotify", "user")},
    {"id": "bandcamp", "name": "Bandcamp", "url": "https://bandcamp.com/{u}", "kind": "html",
     "not_found": ("not found", "sorry"), "found": ("bandcamp", "fan")},
    {"id": "lastfm", "name": "Last.fm", "url": "https://www.last.fm/user/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("last.fm", "user")},
    {"id": "steam", "name": "Steam", "url": "https://steamcommunity.com/id/{u}", "kind": "html",
     "not_found": ("the specified profile could not be found", "error"),
     "found": ("steam", "profile_header")},
    {"id": "xbox", "name": "Xbox", "url": "https://www.xbox.com/en-US/play/user/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("xbox", "gamertag")},
    {"id": "playstation", "name": "PlayStation", "url": "https://psnprofiles.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("psn", "profile")},
    {"id": "roblox", "name": "Roblox", "url": "https://www.roblox.com/users/profile?username={u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("roblox", "profile")},
    {"id": "chess", "name": "Chess.com", "url": "https://www.chess.com/member/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("chess.com", "member")},
    {"id": "lichess", "name": "Lichess", "url": "https://lichess.org/@/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("lichess", "user")},
    {"id": "duolingo", "name": "Duolingo", "url": "https://www.duolingo.com/profile/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("duolingo", "profile")},
    {"id": "goodreads", "name": "Goodreads", "url": "https://www.goodreads.com/{u}", "kind": "html",
     "not_found": ("not found", "page not found"), "found": ("goodreads", "profile")},
    {"id": "letterboxd", "name": "Letterboxd", "url": "https://letterboxd.com/{u}/", "kind": "html",
     "not_found": ("not found", "sorry"), "found": ("letterboxd", "profile")},
    {"id": "myanimelist", "name": "MyAnimeList", "url": "https://myanimelist.net/profile/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("myanimelist", "profile")},
    {"id": "behance", "name": "Behance", "url": "https://www.behance.net/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("behance", "profile")},
    {"id": "dribbble", "name": "Dribbble", "url": "https://dribbble.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("dribbble", "profile")},
    {"id": "deviantart", "name": "DeviantArt", "url": "https://www.deviantart.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("deviantart", "user")},
    {"id": "artstation", "name": "ArtStation", "url": "https://www.artstation.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("artstation", "user")},
    {"id": "producthunt", "name": "Product Hunt", "url": "https://www.producthunt.com/@{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("producthunt", "profile")},
    {"id": "linktree", "name": "Linktree", "url": "https://linktr.ee/{u}", "kind": "html",
     "not_found": ("not found", "couldn't find"), "found": ("linktree", "profile")},
    {"id": "carrd", "name": "Carrd", "url": "https://{u}.carrd.co", "kind": "html",
     "not_found": ("not found", "404"), "found": ("carrd",)},
    {"id": "aboutme", "name": "About.me", "url": "https://about.me/{u}", "kind": "html",
     "not_found": ("page not found", "doesn't exist"), "found": ("aboutme", "profile")},
    {"id": "keybase", "name": "Keybase", "url": "https://keybase.io/{u}", "kind": "keybase"},
    {"id": "buymeacoffee", "name": "Buy Me a Coffee", "url": "https://buymeacoffee.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("buymeacoffee", "profile")},
    {"id": "kofi", "name": "Ko-fi", "url": "https://ko-fi.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("ko-fi", "profile")},
    {"id": "patreon", "name": "Patreon", "url": "https://www.patreon.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("patreon", "creator")},
    {"id": "paypalme", "name": "PayPal.me", "url": "https://paypal.me/{u}", "kind": "html",
     "not_found": ("not found", "couldn't find"), "found": ("paypal",)},
    {"id": "venmo", "name": "Venmo", "url": "https://venmo.com/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("venmo", "profile")},
    {"id": "cashapp", "name": "Cash App", "url": "https://cash.app/${u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("cash", "profile")},
    {"id": "vk", "name": "VK", "url": "https://vk.com/{u}", "kind": "html",
     "not_found": ("not found", "404", "page not found"), "found": ("vk.com", "profile")},
    {"id": "okru", "name": "OK.ru", "url": "https://ok.ru/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("ok.ru", "profile")},
    {"id": "quora", "name": "Quora", "url": "https://www.quora.com/profile/{u}", "kind": "html",
     "not_found": ("not found", "404"), "found": ("quora", "profile")},
    {"id": "wikipedia", "name": "Wikipedia user", "url": "https://en.wikipedia.org/wiki/User:{u}", "kind": "html",
     "not_found": ("does not exist", "no user"), "found": ("user page", "mw-userpage")},
    {"id": "wikipedia_commons", "name": "Wikimedia Commons", "url": "https://commons.wikimedia.org/wiki/User:{u}", "kind": "html",
     "not_found": ("does not exist", "no user"), "found": ("user page",)},
]
